import type { Module } from "../types";

export const MODULES: Module[] = [
  {
    id: "module-1",
    title: "Meet Celly",
    icon: "📱",
    color: "#6C5CE7",
    nodes: [
      {
        id: "m1-n1",
        title: "Sort the apps",
        panels: [
          {
            id: "m1-n1-p1",
            text: "Celly is a phone full of apps.",
            illustration: "phone-with-colorful-app-icons",
          },
          {
            id: "m1-n1-p2",
            text: "Some apps feel essential. Phone, Camera, and Messages help you stay connected and safe.",
            illustration: "phone-screen-essential-apps-row",
          },
          {
            id: "m1-n1-p3",
            text: "Other apps are mostly for fun — like games, photo filters, or short videos. Many apps can run at once, while some stay open quietly in the background.",
            illustration: "phone-screen-fun-apps-row",
          },
          {
            id: "m1-n1-p4",
            text: "Your body is kinda similar. It runs lots of jobs at the same time — not on a screen, but inside you.",
            illustration: "split-phone-and-silhouette-body-transition",
          },
        ],
        game: {
          type: "drag-drop",
          layout: "side-by-side",
          prompt: "Sort the apps",
          items: [
            { id: "phone", label: "Phone", icon: "📞" },
            { id: "games", label: "Games", icon: "🎮" },
            { id: "camera", label: "Camera", icon: "📷" },
            { id: "music", label: "Music", icon: "🎵" },
            { id: "clock", label: "Clock", icon: "🕐" },
            { id: "messages", label: "Messages", icon: "💬" },
            { id: "maps", label: "Maps", icon: "🗺️" },
            { id: "shopping", label: "Shopping", icon: "🛍️" },
            { id: "calendar", label: "Calendar", icon: "📅" },
            { id: "youtube", label: "YouTube", icon: "▶️" },
          ],
          targets: [
            { id: "essential", label: "Essential", icon: "⭐" },
            { id: "fun", label: "Fun", icon: "🎉" },
          ],
          correctMapping: {
            phone: "essential",
            camera: "essential",
            messages: "essential",
            clock: "essential",
            maps: "essential",
            calendar: "essential",
            music: "fun",
            games: "fun",
            shopping: "fun",
            youtube: "fun",
          },
        },
        funFact:
          "A phone typically runs about 30 apps, but your body runs way more systems than that — all at the same time!",
      },
      {
        id: "m1-n2",
        title: "Charge the phone",
        panels: [
          {
            id: "m1-n2-p1",
            text: "All those apps need energy. Without power, the phone screen stays black.",
            illustration: "celly-gray-uncharged",
          },
          {
            id: "m1-n2-p2",
            text: "Plugging in the phone and letting it charge refills the battery.\nElectricity is the phone's power source.",
            illustration: "celly-with-charger",
          },
          {
            id: "m1-n2-p3",
            text: "When the battery is full enough, every app can work again.",
            illustration: "celly-fully-charged",
          },
        ],
        game: {
          type: "snake",
          prompt: "Charge the phone!",
          gridWidth: 15,
          gridHeight: 12,
          plugStart: { x: 1, y: 10 },
          socketPos: { x: 13, y: 1 },
          obstacles: [
            { x: 4, y: 2, w: 1, h: 6 },
            { x: 8, y: 4, w: 1, h: 6 },
            { x: 11, y: 1, w: 1, h: 5 },
          ],
          collectibles: [
            { x: 3, y: 9, emoji: "⚡" },
            { x: 6, y: 3, emoji: "⚡" },
            { x: 10, y: 8, emoji: "⚡" },
          ],
          collectiblesRequired: 3,
        },
        funFact:
          "A fully charged phone battery can last about 10-12 hours.",
      },
      {
        id: "m1-n3",
        title: "The body's apps",
        panels: [
          {
            id: "m1-n3-p1",
            text: "Your body has many \"apps\" running all the time!",
            illustration: "body-apps-overview",
          },
          {
            id: "m1-n3-p2",
            text: "Your brain is like a control center. It helps you think, feel, and decide.",
            illustration: "brain-icon-large",
          },
          {
            id: "m1-n3-p3",
            text: "Your heart pumps blood like a steady drumbeat. It never takes a day off.",
            illustration: "heart-icon-large",
          },
          {
            id: "m1-n3-p4",
            text: "Your lungs pull in air and swap fresh oxygen for used-up air you breathe out.",
            illustration: "lungs-icon-large",
          },
          {
            id: "m1-n3-p5",
            text: "Your digestive system breaks down and absorbs food.",
            illustration: "stomach-icon-large",
          },
          {
            id: "m1-n3-p6",
            text: "Bones grow and provide structure for your body.",
            illustration: "bones-icon-large",
          },
          {
            id: "m1-n3-p7",
            text: "Muscles help you move your body.",
            illustration: "muscles-icon-large",
          },
          {
            id: "m1-n3-p8",
            text: "Skin helps regulate your body temperature and protects you.",
            illustration: "skin-icon-large",
          },
          {
            id: "m1-n3-p9",
            text: "Brain, heart, lungs, bones, muscles, digestion, skin and more — all functioning together, right now.",
            illustration: "all-systems-running",
          },
        ],
        game: {
          type: "drag-drop",
          layout: "body-map",
          prompt: "The body's apps",
          items: [
            { id: "brain", label: "Brain", icon: "🧠" },
            { id: "heart", label: "Heart", icon: "❤️" },
            { id: "lungs", label: "Lungs", icon: "🫁" },
            { id: "stomach", label: "Stomach", icon: "stomach.png" },
            { id: "muscles", label: "Muscles", icon: "💪" },
            { id: "bones", label: "Bones", icon: "🦴" },
            { id: "skin", label: "Skin", icon: "🤚" },
          ],
          targets: [
            { id: "head", label: "Head", icon: "👤" },
            { id: "chest", label: "Chest", icon: "🫀" },
            { id: "left-arm", label: "Left arm", icon: "💪" },
            { id: "right-arm", label: "Right arm", icon: "💪" },
            { id: "left-leg", label: "Left leg", icon: "🦵" },
            { id: "right-leg", label: "Right leg", icon: "🦵" },
          ],
          correctMapping: {
            brain: "head",
            heart: "chest",
            lungs: "chest",
            stomach: "chest",
            muscles: "*limbs",
            bones: "*limbs",
            skin: "*limbs",
          },
        },
        funFact:
          "Your brain uses about 20% of all the energy your body makes — even though it's only about 2% of your body weight!",
      },
      {
        id: "m1-n4",
        title: "Charge the body",
        panels: [
          {
            id: "m1-n4-p1",
            text: "Your body also needs to recharge with food, water, and sleep every single day!",
            illustration: "three-batteries-overview",
          },
          {
            id: "m1-n4-p2",
            text: "Food is your main everyday energy source. It helps you think, move, and grow.",
            illustration: "plate-of-supportive-foods-energy-rays",
          },
          {
            id: "m1-n4-p3",
            text: "Drinking enough fluids keeps blood and nutrients moving smoothly.",
            illustration: "water-hydration-simple",
          },
          {
            id: "m1-n4-p4",
            text: "Sleep is recovery time. Your body repairs, sorts memories, and gets ready for tomorrow.",
            illustration: "moon-pillow-kid-sleeping-cozy",
          },
        ],
        game: {
          type: "snake-collect",
          prompt: "Charge your \"battery\"!",
          gridWidth: 18,
          gridHeight: 14,
          startPos: { x: 9, y: 7 },
          goodItems: ["🍎", "🥦", "🍞", "💧", "🛏️", "🍗", "🍉", "🥕", "🧃", "😴", "🥛", "🍌"],
          badItems: ["🔋", "📶", "🔌", "⚡", "📱"],
          totalSpawns: 22,
          obstacles: [
            { x: 4, y: 3, w: 1, h: 4 },
            { x: 9, y: 1, w: 1, h: 3 },
            { x: 13, y: 5, w: 1, h: 2 },
            { x: 13, y: 8, w: 1, h: 2 },
            { x: 6, y: 10, w: 4, h: 1 },
            { x: 15, y: 2, w: 1, h: 3 },
          ],
        },
        funFact:
          "Sleep is when your body does most of its repair work. Your muscles grow, your brain organizes memories, and your immune system recharges — all while you snooze!",
      },
      {
        id: "m1-n5",
        title: "Big stuff!",
        panels: [
          {
            id: "m1-n5-p1",
            text: "We know that food is the body's main fuel source. You need it to move, learn, and heal.",
            illustration: "food-main-fuel",
          },
          {
            id: "m1-n5-p2",
            text: "There are three main food groups that your body needs in large amounts.",
            illustration: "mystery-boxes-clickable",
          },
          {
            id: "m1-n5-p3",
            text: "Carbohydrates are mostly found in plant foods.\nThis includes foods like fruits, vegetables, and grains such as rice and wheat.\nFoods made from wheat—like bread, pasta, and cereals—are also carbohydrates.",
            illustration: "what-are-carbs",
          },
          {
            id: "m1-n5-p4",
            text: "Protein is found in animal foods like chicken, fish, eggs, and dairy—but also in some plant foods like beans and nuts.",
            illustration: "what-is-protein",
          },
          {
            id: "m1-n5-p5",
            text: "Fats are found in foods that contain oils, like olive oil, butter, nuts, seeds, and avocados.",
            illustration: "what-are-fats",
          },
          {
            id: "m1-n5-p6",
            text: "Here's a simple way to think about it.",
            illustration: "macros-summary",
          },
        ],
        game: {
          type: "drag-drop",
          prompt: "Sort the foods!",
          layout: "mystery-boxes",
          items: [
            { id: "chicken", label: "Chicken", icon: "🍗" },
            { id: "bread", label: "Bread", icon: "🍞" },
            { id: "avocado", label: "Avocado", icon: "🥑" },
            { id: "watermelon", label: "Watermelon", icon: "🍉" },
            { id: "egg", label: "Egg", icon: "🥚" },
            { id: "butter", label: "Butter", icon: "🧈" },
            { id: "pasta", label: "Pasta", icon: "🍝" },
            { id: "sausage", label: "Sausage", icon: "foods/sausage.png" },
            { id: "cheese", label: "Cheese", icon: "🧀" },
            { id: "orange", label: "Orange", icon: "🍊" },
            { id: "fish", label: "Fish", icon: "🐟" },
            { id: "cookie", label: "Cookie", icon: "🍪" },
            { id: "peanut-butter", label: "Peanut butter", icon: "foods/peanut-butter.png" },
            { id: "rice", label: "Rice", icon: "🍚" },
            { id: "meat", label: "Meat", icon: "🥩" },
            { id: "strawberry", label: "Strawberry", icon: "🍓" },
            { id: "olive", label: "Olive", icon: "🫒" },
            { id: "banana", label: "Banana", icon: "🍌" },
            { id: "beans", label: "Beans", icon: "🫘" },
            { id: "peanuts", label: "Peanuts", icon: "🥜" },
            { id: "carrot", label: "Carrot", icon: "🥕" },
            { id: "milk", label: "Milk", icon: "🥛" },
            { id: "broccoli", label: "Broccoli", icon: "🥦" },
            { id: "potato", label: "Potato", icon: "🥔" },
          ],
          targets: [
            { id: "carbs", label: "Carbs", icon: "🍞" },
            { id: "protein", label: "Protein", icon: "🍗" },
            { id: "fats", label: "Fats", icon: "🧈" },
          ],
          correctMapping: {
            bread: "carbs", rice: "carbs", pasta: "carbs", potato: "carbs", banana: "carbs",
            cookie: "carbs", watermelon: "carbs", orange: "carbs", carrot: "carbs",
            broccoli: "carbs", strawberry: "carbs",
            chicken: "protein", meat: "protein", fish: "protein", egg: "protein",
            beans: "protein", milk: "protein", sausage: "protein",
            butter: "fats", avocado: "fats", peanuts: "fats", cheese: "protein", olive: "fats",
            "peanut-butter": "fats",
          },
        },
        funFact:
          "\"Macro\" means big — because your body needs these in large amounts!",
      },
      {
        id: "m1-n6",
        title: "Catch the food!",
        panels: [
          {
            id: "m1-n6-p1",
            text: "Time to test your skills! Pick a food group and catch the right foods as they fall.",
            illustration: "food-main-fuel",
          },
        ],
        game: {
          type: "catcher",
          prompt: "Catch the food!",
          categories: [
            {
              id: "carbs",
              label: "Carbs",
              icon: "🍞",
              items: ["🍞", "🍚", "🍝", "🥔", "🍌", "🍪", "🍉", "🍊", "🥕", "🥦", "🍅", "🍓"],
            },
            {
              id: "protein",
              label: "Protein",
              icon: "🍗",
              items: ["🍗", "🥩", "🐟", "🥚", "🫘", "🥛", "🌭"],
            },
            {
              id: "fats",
              label: "Fats",
              icon: "🧈",
              items: ["🧈", "🥑", "🥜", "🧀", "🫒"],
            },
          ],
          totalDrops: 25,
          baseFallSpeed: 0.8,
        },
        funFact:
          "Your body uses all three macronutrients together — they're a team!",
      },
    ],
  },
  {
    id: "module-2",
    title: "The Team",
    icon: "🤝",
    color: "#F59E0B",
    nodes: [],
  },
  {
    id: "module-3",
    title: "Cells",
    icon: "🔬",
    color: "#00CEC9",
    nodes: [],
  },
  {
    id: "module-4",
    title: "Carbohydrates",
    icon: "🍞",
    color: "#F59E0B",
    nodes: [],
  },
  {
    id: "module-5",
    title: "Fats",
    icon: "🥑",
    color: "#10B981",
    nodes: [],
  },
  {
    id: "module-6",
    title: "Protein",
    icon: "🍗",
    color: "#8B5CF6",
    nodes: [],
  },
];
